/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    momentos: Momento;
    publicos: Publico;
    etapas: Etapa;
    formatos: Formato;
    numeros: Numero;
    empresas: Empresa;
    depoimentos: Depoimento;
    provaFotos: ProvaFoto;
    frases: Frase;
    shows: Show;
    leads: Lead;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    momentos: MomentosSelect<false> | MomentosSelect<true>;
    publicos: PublicosSelect<false> | PublicosSelect<true>;
    etapas: EtapasSelect<false> | EtapasSelect<true>;
    formatos: FormatosSelect<false> | FormatosSelect<true>;
    numeros: NumerosSelect<false> | NumerosSelect<true>;
    empresas: EmpresasSelect<false> | EmpresasSelect<true>;
    depoimentos: DepoimentosSelect<false> | DepoimentosSelect<true>;
    provaFotos: ProvaFotosSelect<false> | ProvaFotosSelect<true>;
    frases: FrasesSelect<false> | FrasesSelect<true>;
    shows: ShowsSelect<false> | ShowsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    settings: Setting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "momentos".
 */
export interface Momento {
  id: number;
  imagem: number | Media;
  legenda?: string | null;
  destaque?: boolean | null;
  /**
   * Menor número aparece primeiro.
   */
  ordem?: number | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreva o que aparece na foto. Ex.: 'Plateia cantando junto em evento corporativo'.
   */
  alt: string;
  creditos?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicos".
 */
export interface Publico {
  id: number;
  titulo: string;
  /**
   * Aparece em itálico dourado. Ex.: 'A trilha sonora do dia que não se repete.'
   */
  frase?: string | null;
  descricao: string;
  imagem?: (number | null) | Media;
  /**
   * Menor número aparece primeiro.
   */
  ordem?: number | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etapas".
 */
export interface Etapa {
  id: number;
  titulo: string;
  descricao: string;
  /**
   * Menor número aparece primeiro.
   */
  ordem?: number | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formatos".
 */
export interface Formato {
  id: number;
  titulo: string;
  descricao: string;
  /**
   * Ex.: 'Cerimônias, recepções e jantares'
   */
  melhorPara?: string | null;
  /**
   * Menor número aparece primeiro.
   */
  ordem?: number | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "numeros".
 */
export interface Numero {
  id: number;
  /**
   * Ex.: '+300', '+50 mil', '8'
   */
  valor: string;
  /**
   * Ex.: 'Eventos realizados'
   */
  rotulo: string;
  /**
   * Menor número aparece primeiro.
   */
  ordem?: number | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empresas".
 */
export interface Empresa {
  id: number;
  nome: string;
  /**
   * Se não tiver logo, o nome aparece em texto.
   */
  logo?: (number | null) | Media;
  /**
   * Menor número aparece primeiro.
   */
  ordem?: number | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "depoimentos".
 */
export interface Depoimento {
  id: number;
  autor: string;
  /**
   * Ex.: 'RH · Assaí Atacadista'
   */
  cargo?: string | null;
  citacao: string;
  /**
   * Menor número aparece primeiro.
   */
  ordem?: number | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provaFotos".
 */
export interface ProvaFoto {
  id: number;
  /**
   * De preferência a REAÇÃO das pessoas: plateia, sorrisos, brindes — não só o João cantando.
   */
  imagem: number | Media;
  legenda?: string | null;
  /**
   * Menor número aparece primeiro.
   */
  ordem?: number | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frases".
 */
export interface Frase {
  id: number;
  texto: string;
  /**
   * Menor número aparece primeiro.
   */
  ordem?: number | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shows".
 */
export interface Show {
  id: number;
  titulo: string;
  data: string;
  local: string;
  cidade: string;
  uf: string;
  descricao?: string | null;
  /**
   * Deixe vazio para o botão levar ao WhatsApp.
   */
  linkIngressos?: string | null;
  cancelado?: boolean | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  nome: string;
  telefone?: string | null;
  email?: string | null;
  tipoEvento?: string | null;
  pessoas?: string | null;
  atmosfera?: string | null;
  mensagem?: string | null;
  status?: ('novo' | 'conversando' | 'fechado' | 'perdido') | null;
  /**
   * Só você vê. Não aparece no site.
   */
  anotacoes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nome: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'momentos';
        value: number | Momento;
      } | null)
    | ({
        relationTo: 'publicos';
        value: number | Publico;
      } | null)
    | ({
        relationTo: 'etapas';
        value: number | Etapa;
      } | null)
    | ({
        relationTo: 'formatos';
        value: number | Formato;
      } | null)
    | ({
        relationTo: 'numeros';
        value: number | Numero;
      } | null)
    | ({
        relationTo: 'empresas';
        value: number | Empresa;
      } | null)
    | ({
        relationTo: 'depoimentos';
        value: number | Depoimento;
      } | null)
    | ({
        relationTo: 'provaFotos';
        value: number | ProvaFoto;
      } | null)
    | ({
        relationTo: 'frases';
        value: number | Frase;
      } | null)
    | ({
        relationTo: 'shows';
        value: number | Show;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "momentos_select".
 */
export interface MomentosSelect<T extends boolean = true> {
  imagem?: T;
  legenda?: T;
  destaque?: T;
  ordem?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicos_select".
 */
export interface PublicosSelect<T extends boolean = true> {
  titulo?: T;
  frase?: T;
  descricao?: T;
  imagem?: T;
  ordem?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etapas_select".
 */
export interface EtapasSelect<T extends boolean = true> {
  titulo?: T;
  descricao?: T;
  ordem?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formatos_select".
 */
export interface FormatosSelect<T extends boolean = true> {
  titulo?: T;
  descricao?: T;
  melhorPara?: T;
  ordem?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "numeros_select".
 */
export interface NumerosSelect<T extends boolean = true> {
  valor?: T;
  rotulo?: T;
  ordem?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empresas_select".
 */
export interface EmpresasSelect<T extends boolean = true> {
  nome?: T;
  logo?: T;
  ordem?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "depoimentos_select".
 */
export interface DepoimentosSelect<T extends boolean = true> {
  autor?: T;
  cargo?: T;
  citacao?: T;
  ordem?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provaFotos_select".
 */
export interface ProvaFotosSelect<T extends boolean = true> {
  imagem?: T;
  legenda?: T;
  ordem?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frases_select".
 */
export interface FrasesSelect<T extends boolean = true> {
  texto?: T;
  ordem?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shows_select".
 */
export interface ShowsSelect<T extends boolean = true> {
  titulo?: T;
  data?: T;
  local?: T;
  cidade?: T;
  uf?: T;
  descricao?: T;
  linkIngressos?: T;
  cancelado?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  nome?: T;
  telefone?: T;
  email?: T;
  tipoEvento?: T;
  pessoas?: T;
  atmosfera?: T;
  mensagem?: T;
  status?: T;
  anotacoes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  creditos?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nome?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroEyebrow?: string | null;
  /**
   * ⚠️ Promessa da marca, definida no posicionamento.
   */
  heroLinha1: string;
  /**
   * ⚠️ Promessa da marca, definida no posicionamento.
   */
  heroLinha2: string;
  heroSubtitulo: string;
  /**
   * Compilado de eventos: casamentos, corporativo, plateia, brindes, luzes. Melhor qualidade. Se vazio, tenta o link do YouTube; senão a imagem.
   */
  heroVideo?: (number | null) | Media;
  /**
   * Cole o link de um vídeo do YouTube para usar de fundo, sem subir arquivo. Toca mudo, em loop, sem controles nem legenda. Prefira um vídeo HORIZONTAL. O arquivo acima tem prioridade sobre o link.
   */
  heroVideoYoutube?: string | null;
  /**
   * Ex.: 12 começa aos 12s. Vazio = do início.
   */
  heroVideoInicio?: number | null;
  /**
   * Ex.: 30 corta aos 30s e reinicia o trecho. Vazio = até o fim.
   */
  heroVideoFim?: number | null;
  heroImagem?: (number | null) | Media;
  heroCta1?: string | null;
  heroCta2?: string | null;
  manifestoEyebrow?: string | null;
  /**
   * Arraste para reordenar. O primeiro aparece em destaque maior.
   */
  manifestoParagrafos?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  manifestoFecho1?: string | null;
  manifestoFecho2?: string | null;
  momentosEyebrow?: string | null;
  momentosTitulo?: string | null;
  momentosLead?: string | null;
  publicosEyebrow?: string | null;
  publicosTitulo?: string | null;
  publicosLead?: string | null;
  processoEyebrow?: string | null;
  processoTitulo?: string | null;
  processoLead?: string | null;
  formatosEyebrow?: string | null;
  formatosTitulo?: string | null;
  formatosLead?: string | null;
  provaEyebrow?: string | null;
  provaTitulo?: string | null;
  empresasTitulo?: string | null;
  agendaEyebrow?: string | null;
  agendaTitulo?: string | null;
  artistaEyebrow?: string | null;
  artistaNome?: string | null;
  artistaHeadline?: string | null;
  artistaBio: string;
  artistaFoto?: (number | null) | Media;
  /**
   * Playlist é o recomendado: você monta a ordem no app do Spotify e ela aparece igual aqui.
   */
  spotifyTipo?: ('artist' | 'playlist' | 'album') | null;
  /**
   * No Spotify: Compartilhar → Copiar link. Cole aqui só a parte depois de /artist/ ou /playlist/.
   */
  spotifyId?: string | null;
  kitEyebrow?: string | null;
  kitTitulo?: string | null;
  kitLead?: string | null;
  kitItens?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  kitCta?: string | null;
  contatoEyebrow?: string | null;
  contatoTitulo?: string | null;
  contatoLead?: string | null;
  /**
   * Arraste para reordenar.
   */
  contatoPerguntas?:
    | {
        pergunta: string;
        dica?: string | null;
        id?: string | null;
      }[]
    | null;
  contatoBotao?: string | null;
  contatoNota?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * PNG com FUNDO TRANSPARENTE, deitado (horizontal). Recomendado ~800×400px. A logo é clara — feita para fundo escuro. Se vazio, usa a logo atual do João.
   */
  logo?: (number | null) | Media;
  /**
   * PNG QUADRADO, 512×512px (mínimo 256×256). Simples e legível bem pequeno — só o símbolo, sem texto. Se vazio, usa o favicon atual.
   */
  favicon?: (number | null) | Media;
  /**
   * Ex.: 5511986894866 — 55 (Brasil) + DDD + número.
   */
  whatsapp: string;
  whatsappExibicao?: string | null;
  cidade?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  facebook?: string | null;
  spotify?: string | null;
  seoTitulo?: string | null;
  seoDescricao?: string | null;
  /**
   * Aparece ao mandar o link no WhatsApp/Instagram. Ideal: 1200×630px.
   */
  ogImagem?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroLinha1?: T;
  heroLinha2?: T;
  heroSubtitulo?: T;
  heroVideo?: T;
  heroVideoYoutube?: T;
  heroVideoInicio?: T;
  heroVideoFim?: T;
  heroImagem?: T;
  heroCta1?: T;
  heroCta2?: T;
  manifestoEyebrow?: T;
  manifestoParagrafos?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  manifestoFecho1?: T;
  manifestoFecho2?: T;
  momentosEyebrow?: T;
  momentosTitulo?: T;
  momentosLead?: T;
  publicosEyebrow?: T;
  publicosTitulo?: T;
  publicosLead?: T;
  processoEyebrow?: T;
  processoTitulo?: T;
  processoLead?: T;
  formatosEyebrow?: T;
  formatosTitulo?: T;
  formatosLead?: T;
  provaEyebrow?: T;
  provaTitulo?: T;
  empresasTitulo?: T;
  agendaEyebrow?: T;
  agendaTitulo?: T;
  artistaEyebrow?: T;
  artistaNome?: T;
  artistaHeadline?: T;
  artistaBio?: T;
  artistaFoto?: T;
  spotifyTipo?: T;
  spotifyId?: T;
  kitEyebrow?: T;
  kitTitulo?: T;
  kitLead?: T;
  kitItens?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  kitCta?: T;
  contatoEyebrow?: T;
  contatoTitulo?: T;
  contatoLead?: T;
  contatoPerguntas?:
    | T
    | {
        pergunta?: T;
        dica?: T;
        id?: T;
      };
  contatoBotao?: T;
  contatoNota?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  logo?: T;
  favicon?: T;
  whatsapp?: T;
  whatsappExibicao?: T;
  cidade?: T;
  instagram?: T;
  youtube?: T;
  facebook?: T;
  spotify?: T;
  seoTitulo?: T;
  seoDescricao?: T;
  ogImagem?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}